# Generated by Django 4.1.7 on 2023-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='nippomodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='nippomodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
