# Generated by Django 4.1.7 on 2023-04-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0002_alter_nippomodel_content_alter_nippomodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nippomodel',
            options={'verbose_name': '日報', 'verbose_name_plural': '日報'},
        ),
    ]
