# Generated by Django 4.1.7 on 2023-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0006_nippomodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
